// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *GitApplication) DeepCopyInto(out *GitApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GitApplication) DeepCopy() *GitApplication {
	if in == nil {
		return nil
	}
	out := new(GitApplication)
	in.DeepCopyInto(out)
	return out
}

func (in *GitApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GitApplicationList) DeepCopyInto(out *GitApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GitApplicationList) DeepCopy() *GitApplicationList {
	if in == nil {
		return nil
	}
	out := new(GitApplicationList)
	in.DeepCopyInto(out)
	return out
}

func (in *GitApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GitApplicationSpec) DeepCopyInto(out *GitApplicationSpec) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmConfig)
		**out = **in
	}
	if in.SyncPolicy != nil {
		in, out := &in.SyncPolicy, &out.SyncPolicy
		*out = new(SyncPolicy)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		**out = **in
	}
}

func (in *GitApplicationSpec) DeepCopy() *GitApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(GitApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HelmConfig) DeepCopyInto(out *HelmConfig) {
	*out = *in
}

func (in *HelmConfig) DeepCopy() *HelmConfig {
	if in == nil {
		return nil
	}
	out := new(HelmConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncPolicy) DeepCopyInto(out *SyncPolicy) {
	*out = *in
}

func (in *SyncPolicy) DeepCopy() *SyncPolicy {
	if in == nil {
		return nil
	}
	out := new(SyncPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackConfig)
		**out = **in
	}
}

func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
}

func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
}

func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *GitApplicationStatus) DeepCopyInto(out *GitApplicationStatus) {
	*out = *in
	if in.LastSyncAt != nil {
		in, out := &in.LastSyncAt, &out.LastSyncAt
		*out = (*in).DeepCopy()
	}
	if in.PreviousRevisions != nil {
		in, out := &in.PreviousRevisions, &out.PreviousRevisions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GitApplicationStatus) DeepCopy() *GitApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(GitApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
}

func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}
