export type SyncStatus = "Synced" | "OutOfSync" | "Syncing" | "Unknown"
export type HealthStatus = "Healthy" | "Degraded" | "Progressing" | "Missing" | "Unknown"
export type ManifestType = "Raw" | "Helm"
export type SyncPolicyType = "Automated" | "Manual"

export interface Deployment {
  id: string
  name: string
  namespace: string
  project: string
  repoURL: string
  branch: string
  path: string
  manifestType: ManifestType
  targetCluster: string
  syncPolicy: SyncPolicyType
  syncStatus: SyncStatus
  healthStatus: HealthStatus
  revision: string
  lastSyncAt: string | null
  resourceCount: number
  autoSync: boolean
  prune: boolean
  selfHeal: boolean
}

export const syncStatuses: SyncStatus[] = ["Synced", "OutOfSync", "Syncing", "Unknown"]
export const healthStatuses: HealthStatus[] = ["Healthy", "Degraded", "Progressing", "Missing", "Unknown"]
export const manifestTypes: ManifestType[] = ["Raw", "Helm"]
export const syncPolicyTypes: SyncPolicyType[] = ["Automated", "Manual"]

export const mockDeployments: Deployment[] = [
  {
    id: "1",
    name: "checkout-service",
    namespace: "checkout",
    project: "prod-apps",
    repoURL: "https://github.com/acme/checkout",
    branch: "main",
    path: "/services/checkout",
    manifestType: "Raw",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "a1b2c3d",
    lastSyncAt: "2026-08-30T06:12:00Z",
    resourceCount: 12,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "2",
    name: "catalog-service",
    namespace: "catalog",
    project: "prod-apps",
    repoURL: "https://github.com/acme/catalog",
    branch: "main",
    path: "/services/catalog",
    manifestType: "Helm",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "OutOfSync",
    healthStatus: "Degraded",
    revision: "e4f5g6h",
    lastSyncAt: "2026-08-30T04:30:00Z",
    resourceCount: 8,
    autoSync: true,
    prune: true,
    selfHeal: false,
  },
  {
    id: "3",
    name: "api-gateway",
    namespace: "gateway",
    project: "infra",
    repoURL: "https://github.com/acme/platform-gateway",
    branch: "release",
    path: "/",
    manifestType: "Raw",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Manual",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "i7j8k9l",
    lastSyncAt: "2026-08-29T22:15:00Z",
    resourceCount: 5,
    autoSync: false,
    prune: false,
    selfHeal: false,
  },
  {
    id: "4",
    name: "user-service",
    namespace: "users",
    project: "prod-apps",
    repoURL: "https://github.com/acme/user-service",
    branch: "main",
    path: "/deploy",
    manifestType: "Helm",
    targetCluster: "staging-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Syncing",
    healthStatus: "Progressing",
    revision: "m0n1o2p",
    lastSyncAt: "2026-08-30T09:00:00Z",
    resourceCount: 15,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "5",
    name: "payment-service",
    namespace: "payments",
    project: "prod-apps",
    repoURL: "https://github.com/acme/payments",
    branch: "main",
    path: "/k8s",
    manifestType: "Raw",
    targetCluster: "prod-cluster-eu (eu-west-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "q3r4s5t",
    lastSyncAt: "2026-08-30T07:45:00Z",
    resourceCount: 20,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "6",
    name: "notification-service",
    namespace: "notifications",
    project: "infra",
    repoURL: "https://github.com/acme/notifications",
    branch: "main",
    path: "/manifests",
    manifestType: "Raw",
    targetCluster: "staging-cluster (us-east-1)",
    syncPolicy: "Manual",
    syncStatus: "OutOfSync",
    healthStatus: "Missing",
    revision: "u6v7w8x",
    lastSyncAt: "2026-08-28T14:20:00Z",
    resourceCount: 3,
    autoSync: false,
    prune: false,
    selfHeal: false,
  },
  {
    id: "7",
    name: "search-service",
    namespace: "search",
    project: "prod-apps",
    repoURL: "https://github.com/acme/search",
    branch: "develop",
    path: "/helm",
    manifestType: "Helm",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Degraded",
    revision: "y9z0a1b",
    lastSyncAt: "2026-08-30T08:30:00Z",
    resourceCount: 7,
    autoSync: true,
    prune: true,
    selfHeal: false,
  },
  {
    id: "8",
    name: "analytics-pipeline",
    namespace: "analytics",
    project: "data",
    repoURL: "https://github.com/acme/analytics",
    branch: "main",
    path: "/deploy",
    manifestType: "Raw",
    targetCluster: "prod-cluster-eu (eu-west-1)",
    syncPolicy: "Automated",
    syncStatus: "Unknown",
    healthStatus: "Unknown",
    revision: "c2d3e4f",
    lastSyncAt: null,
    resourceCount: 0,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "9",
    name: "auth-service",
    namespace: "auth",
    project: "infra",
    repoURL: "https://github.com/acme/auth",
    branch: "main",
    path: "/k8s",
    manifestType: "Raw",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "g5h6i7j",
    lastSyncAt: "2026-08-30T05:00:00Z",
    resourceCount: 10,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "10",
    name: "inventory-service",
    namespace: "inventory",
    project: "prod-apps",
    repoURL: "https://github.com/acme/inventory",
    branch: "main",
    path: "/services/inventory",
    manifestType: "Helm",
    targetCluster: "staging-cluster (us-east-1)",
    syncPolicy: "Manual",
    syncStatus: "Synced",
    healthStatus: "Progressing",
    revision: "k8l9m0n",
    lastSyncAt: "2026-08-30T03:15:00Z",
    resourceCount: 6,
    autoSync: false,
    prune: false,
    selfHeal: false,
  },
  {
    id: "11",
    name: "billing-service",
    namespace: "billing",
    project: "prod-apps",
    repoURL: "https://github.com/acme/billing",
    branch: "release",
    path: "/",
    manifestType: "Raw",
    targetCluster: "prod-cluster-eu (eu-west-1)",
    syncPolicy: "Automated",
    syncStatus: "OutOfSync",
    healthStatus: "Healthy",
    revision: "o1p2q3r",
    lastSyncAt: "2026-08-29T18:00:00Z",
    resourceCount: 14,
    autoSync: true,
    prune: false,
    selfHeal: true,
  },
  {
    id: "12",
    name: "logging-agent",
    namespace: "logging",
    project: "infra",
    repoURL: "https://github.com/acme/logging",
    branch: "main",
    path: "/deploy",
    manifestType: "Raw",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "s4t5u6v",
    lastSyncAt: "2026-08-30T01:30:00Z",
    resourceCount: 4,
    autoSync: true,
    prune: true,
    selfHeal: false,
  },
  {
    id: "13",
    name: "feature-flags-service",
    namespace: "features",
    project: "data",
    repoURL: "https://github.com/acme/feature-flags",
    branch: "main",
    path: "/k8s",
    manifestType: "Helm",
    targetCluster: "staging-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Syncing",
    healthStatus: "Healthy",
    revision: "w7x8y9z",
    lastSyncAt: "2026-08-30T09:15:00Z",
    resourceCount: 9,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
  {
    id: "14",
    name: "rate-limiter",
    namespace: "gateway",
    project: "infra",
    repoURL: "https://github.com/acme/rate-limiter",
    branch: "main",
    path: "/",
    manifestType: "Raw",
    targetCluster: "prod-cluster-eu (eu-west-1)",
    syncPolicy: "Manual",
    syncStatus: "Synced",
    healthStatus: "Degraded",
    revision: "a0b1c2d",
    lastSyncAt: "2026-08-29T10:00:00Z",
    resourceCount: 2,
    autoSync: false,
    prune: false,
    selfHeal: false,
  },
  {
    id: "15",
    name: "data-warehouse-sync",
    namespace: "analytics",
    project: "data",
    repoURL: "https://github.com/acme/warehouse-sync",
    branch: "main",
    path: "/deploy",
    manifestType: "Raw",
    targetCluster: "prod-cluster (us-east-1)",
    syncPolicy: "Automated",
    syncStatus: "Synced",
    healthStatus: "Healthy",
    revision: "e3f4g5h",
    lastSyncAt: "2026-08-30T02:45:00Z",
    resourceCount: 11,
    autoSync: true,
    prune: true,
    selfHeal: true,
  },
]

export const clusters = [
  "prod-cluster (us-east-1)",
  "staging-cluster (us-east-1)",
  "prod-cluster-eu (eu-west-1)",
]

export const projects = ["prod-apps", "infra", "data"]
